version: '3.9'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8592

    volumes:
      - database-postgres:/var/lib/postgresql/data
    networks:
      - clean_ecommerce-network

  app:
    image: abhishekabi047/lapify:latest
    ports:
      - 8080:8080
    environment:
      DBHOST: "postgres"
      DBUSER: "postgres"
      DBPASSWORD: "8592"
      DBPORT: "5432"
      DBName: "ecom"
    depends_on:
      - postgres
    restart: on-failure
    networks:
      - clean_ecommerce-network

volumes:
  database-postgres:

networks:
  clean_ecommerce-network:
    driver: bridge